export const ROUTES = {
  asCustomerSiteDetails: "/customer/:customerId/sites/:id",
  asCustomerSites: "/customer/:customerId/sites",
  asCustomerNewSite: "/customer/:customerId/sites/new",
  asCustomersConnectionDetails: "/customer/:customerId/connections/:id",
  asCustomerConnections: "/customer/:customerId/connections",

  home: "/",
  login: "/login",
  booking:"/booking",
  asCustomerBooking:"/customer/:customerId/booking",
  asCustomerCreateBooking: "/customer/createBooking",
  signup: "/signup",
  operators: "/operators",
  operatorsAdd: "/operators/add",
  customersAdd: "/customers/add",
  operatorsEdit: "/operators/edit/:id",
  operatorsView: "/operators/view/:id",
  operatorCustomerAdd: "/customer/add",
  services: "/services",
  servicesDetails: "/services/:id",
  newSimDetails: "/sims/:simId",
  sims: "/sims",
  simsAdd: "/sims/add",
  devices: "/device-groups",
  deviceDetails: "/device-groups/:id",
  reservations: "/reservations",
  reservationsAdd: "/reservations/add",
  reservationDetails: "/reservations/:id",
  review: "/members-area/review",
  store: "/store",
  asCustomerStore: "/customer/:customerId/store",
  news: "/news",
  asCustomerNews: "/customer/:customerId/news",
  faqs: "/faqs",
  asCustomerFaqs: "/customer/:customerId/faqs",
  coaching: "/coaching",
  asCustomerCoaching: "/customer/:customerId/coaching",
  membersArea: "/members-area",
  asCustomerMembersArea: "/customer/:customerId/members-area",
  aboutUs: "/about-us",
  asCustomerAboutUs: "/customer/:customerId/about-us",
  sites: "/sites",
  siteDetails: "/sites/:id",
  asCustomerReservations: "/customer/:customerId/reservations",
  users: "/users",
  usersAdd: "/users/add",
  usersEdit: "/users/edit/:userId",
  usersView: "/users/view/:userId",
  asCustomerHome: "/customer/:customerId",
  asCustomerServices: "/customer/:customerId/services",
  asCustomerServicesDetails: "/customer/:customerId/services/:id",
  asCustomerSims: "/customer/:customerId/sims",
  asCustomerSimsAdd: "/customer/:customerId/sims/add",
  asCustomerDevices: "/customer/:customerId/device-groups",
  asCustomerDeviceAdd: "/customer/:customerId/device-groups/add",
  asCustomerUsers: "/customer/:customerId/users",
  asCustomerUserAdd: "/customer/:customerId/users/add",
  asOperatorUserAdd: "/operator/users/add",
  asCustomerUserEdit: "/customer/:customerId/users/edit/:userId",
  asCustomerUserView: "/customer/:customerId/users/view/:userId",
  asCustomersDeviceDetails: "/customer/:customerId/device-groups/:id",
  asCustomerSimDetails: "/customer/:customerId/device-groups/:id/sims/:simId",
  asCustomerSimDetailsNew: "/customer/:customerId/sims/:simId",
  rest: "*",
};

export const LAYOUTS = {
  customer: [
    { name: "dashboard", icon: "home", route: ROUTES.home },
    { name: "news", icon: "apartment-building", route: ROUTES.news },
    { name: "faqs", icon: "apartment-building", route: ROUTES.faqs },
    // { name: "coaching", icon: "apartment-building", route: ROUTES.coaching },
    // { name: "store", icon: "apartment-building", route: ROUTES.store },
    { name: "membersArea", icon: "apartment-building", route: ROUTES.membersArea },
  ],
  operator: [
    { name: "customers", icon: "user-account", route: ROUTES.home },
    { name: "users", icon: "headphones", route: ROUTES.users },
  ],
  asCustomer: [
    { name: "dashboard", icon: "home", route: ROUTES.asCustomerHome },
    { name: "news", icon: "apartment-building", route: ROUTES.asCustomerNews },
    { name: "faqs", icon: "apartment-building", route: ROUTES.asCustomerFaqs },
    // { name: "coaching", icon: "apartment-building", route: ROUTES.asCustomerCoaching },
    // { name: "store", icon: "apartment-building", route: ROUTES.asCustomerStore },
    { name: "reservations", icon: "apartment-building", route: ROUTES.asCustomerBooking },
  ],
};
