export const typography = {
  fontFamily: ["Sans Regular"],
  h1: {
    fontFamily: "Sans Light",
    fontStyle: "normal",
    fontWeight: 300,
    fontSize: "48px",
    lineHeight: "56px",
  },
  h2: {
    fontFamily: "Sans Light",
    fontStyle: "normal",
    fontWeight: 300,
    fontSize: "40px",
    lineHeight: "48px",
  },
  h3: {
    fontFamily: "Sans Light",
    fontStyle: "normal",
    fontWeight: 300,
    fontSize: "32px",
    lineHeight: "40px",
  },
  h4: {
    fontFamily: "Sans Light",
    fontStyle: "normal",
    fontWeight: 300,
    fontSize: "28px",
    lineHeight: "32px",
  },
  h5: {
    fontFamily: "Sans Medium",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "20px",
    lineHeight: "28px",
  },
  h6: {
    fontFamily: "Sans Medium",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "20px",
  },
  body1: {
    fontFamily: "Sans Regular",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "20px",
    lineHeight: "28px",
  },
  body2: {
    fontFamily: "Sans Regular",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "24px",
  },
  body3: {
    fontFamily: "Sans Regular",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "24px",
  },
  caption: {
    fontFamily: "Sans Regular",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
  },
  caption2: {
    fontFamily: "Sans Medium",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "20px",
  },
  subtitle: {
    fontFamily: "Sans Medium",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "24px",
  },
  subtitle1: {
    fontFamily: "Sans Medium",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "24px",
  },
  subtitle2: {
    fontFamily: "Sans Medium",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "20px",
  },
  preset1: {
    fontFamily: "Sans Medium",
    fontWeight: 600,
    fontSize: "14px",
    textTransform: "uppercase",
  },
};
