version: "3"

volumes:
  node_modules:
  cache:
services:
  dev:
    ipc: host
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm i
    ports:
      - "3000:3000"
      - "3100:3100"
    volumes:
      - ./src:/src
      - node_modules:/src/node_modules
      - cache:/root/.cache/